
#[API]
#base_url = https://jsonplaceholder.typicode.com
#timeout = 10
#log_level = DEBUG

[DEFAULT]
timeout = 10
log_level = DEBUG
env = DEV

[DEV]
base_url = https://jsonplaceholder.typicode.com

[UAT]
base_url = https://uat.jsonplaceholder.typicode.com

